sequenceDiagram
    participant Member
    participant CountryAdmin
    participant Partner
    participant PartnerCountryAdmin


    Member->>CountryAdmin: 取引リクエストを送信
    CountryAdmin->>CountryAdmin: リクエストを審査
    CountryAdmin->>PartnerCountryAdmin: リクエストをパートナー国代表に転送
    PartnerCountryAdmin->>PartnerCountryAdmin: リクエストを審査
    PartnerCountryAdmin-->>Member: 適切な候補者リスト（最大3件）を送信
    Member->>Partner: 候補者とやり取り
    Member->>CountryAdmin: 選択結果を送信
    CountryAdmin->>Partner: 結果を通知
